<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Purchase Requests Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .status {
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }
        .status-draft { background-color: #fef3cd; color: #856404; }
        .status-pending { background-color: #fff3cd; color: #856404; }
        .status-approved { background-color: #d1e7dd; color: #0f5132; }
        .status-rejected { background-color: #f8d7da; color: #721c24; }
        .status-po-generated { background-color: #d1ecf1; color: #0c5460; }
        .status-completed { background-color: #e2e3e5; color: #41464b; }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Purchase Requests Report</h1>
        <p>Generated on {{ date('F d, Y H:i:s') }}</p>
        <p>Total Records: {{ count($purchaseRequests) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>PR Number</th>
                <th>Entity Name</th>
                <th>Fund Cluster</th>
                <th>Office/Section</th>
                <th>Total Amount</th>
                <th>Status</th>
                <th>Date Created</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($purchaseRequests as $index => $pr)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $pr->pr_number }}</td>
                    <td>{{ $pr->entity_name }}</td>
                    <td>{{ $pr->fund_cluster }}</td>
                    <td>{{ $pr->office_section }}</td>
                    <td>₱{{ number_format($pr->total, 2) }}</td>
                    <td>
                        <span class="status status-{{ str_replace('_', '-', $pr->status) }}">
                            {{ ucfirst(str_replace('_', ' ', $pr->status)) }}
                        </span>
                    </td>
                    <td>{{ $pr->created_at->format('M d, Y') }}</td>
                    <td>{{ $pr->date ? \Carbon\Carbon::parse($pr->date)->format('M d, Y') : '' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report was generated by DSWD-PRISM system.</p>
    </div>
</body>
</html>