<x-page-layout>
    <x-slot name="header">
        <x-app-header :homeUrl="route('staff')" :title="$pageTitle ?? __('DSWD-PRISM')" :userName="Auth::user()->first_name .
            (Auth::user()->middle_name ? ' ' . Auth::user()->middle_name : '') .
            ' ' .
            Auth::user()->last_name" :recentActivities="$recentActivities ?? collect()" />
    </x-slot>

    <!-- Main Content -->
    <div class="py-8">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
                <div class="flex items-center justify-between mb-6">
                    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                        {{ __('Generate Purchase Order') }}
                    </h2>
                    <a href="{{ route('staff.pr_review') }}"
                        class="text-blue-600 hover:text-blue-800 text-sm font-medium">
                        ← Back to Request Review
                    </a>
                </div>

                @if ($errors->any())
                    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
                        <ul class="list-disc list-inside">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form method="post" action="{{ route('staff.generate_po.store', $purchaseRequest) }}"
                    class="space-y-6">
                    @csrf

                    <!-- PR Information Section -->
                    <div class="bg-gray-50 p-4 rounded-lg">
                        <h3 class="text-lg font-medium text-gray-900 mb-4">Purchase Request Information</h3>
                        <div class="grid grid-cols-2 gap-4">
                            <div>
                                <label class="block text-sm font-medium text-gray-700">PR Number</label>
                                <input type="text" value="{{ $purchaseRequest->pr_number }}" readonly
                                    class="mt-1 block w-full border-gray-300 rounded-md shadow-sm bg-gray-100">
                            </div>
                            <div>
                                <label class="block text-sm font-medium text-gray-700">Requesting Unit</label>
                                <input type="text"
                                    value="{{ $purchaseRequest->user->first_name }}{{ $purchaseRequest->user->middle_name ? ' ' . $purchaseRequest->user->middle_name : '' }} {{ $purchaseRequest->user->last_name }}"
                                    readonly class="mt-1 block w-full border-gray-300 rounded-md shadow-sm bg-gray-100">
                            </div>
                        </div>
                    </div>

                    <!-- Supplier Information Section -->
                    <div class="bg-blue-50 p-4 rounded-lg">
                        <h3 class="text-lg font-medium text-gray-900 mb-4">Supplier Information</h3>
                        <div class="grid grid-cols-2 gap-4">
                            <div>
                                <label for="supplier_id" class="block text-sm font-medium text-gray-700">Supplier
                                    <span class="text-red-500">*</span></label>
                                <select name="supplier_id" id="supplier_id" required onchange="updateSupplierInfo()"
                                    class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
                                    <option value="">Select Supplier</option>
                                    @foreach ($suppliers as $supplier)
                                        <option value="{{ $supplier->id }}" data-address="{{ $supplier->address }}"
                                            data-tin="{{ $supplier->tin }}">
                                            {{ $supplier->supplier_name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div>
                                <label for="po_number" class="block text-sm font-medium text-gray-700">PO Number</label>
                                <input type="text" name="po_number" id="po_number"
                                    value="{{ $autoGeneratedPONumber }}" readonly
                                    class="mt-1 block w-full border-gray-300 rounded-md shadow-sm bg-gray-100">
                            </div>
                            <div>
                                <label for="supplier_address" class="block text-sm font-medium text-gray-700">Supplier
                                    Address</label>
                                <textarea name="supplier_address" id="supplier_address" rows="2" readonly
                                    class="mt-1 block w-full border-gray-300 rounded-md shadow-sm bg-gray-100"></textarea>
                            </div>
                            <div>
                                <label for="supplier_tin" class="block text-sm font-medium text-gray-700">TIN</label>
                                <input type="text" name="supplier_tin" id="supplier_tin" readonly
                                    class="mt-1 block w-full border-gray-300 rounded-md shadow-sm bg-gray-100">
                            </div>
                        </div>
                    </div>

                    <!-- Procurement Details Section -->
                    <div class="bg-green-50 p-4 rounded-lg">
                        <h3 class="text-lg font-medium text-gray-900 mb-4">Procurement Details</h3>
                        <div class="grid grid-cols-2 gap-4">
                            <div>
                                <label for="mode_of_procurement" class="block text-sm font-medium text-gray-700">Mode of
                                    Procurement <span class="text-red-500">*</span></label>
                                <select name="mode_of_procurement" id="mode_of_procurement" required
                                    class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
                                    <option value="">Select Mode</option>
                                    <option value="Shopping">Shopping</option>
                                    <option value="Small Value Procurement">Small Value Procurement</option>
                                    <option value="Direct Contracting">Direct Contracting</option>
                                    <option value="Limited Source Bidding">Limited Source Bidding</option>
                                    <option value="Competitive Bidding">Competitive Bidding</option>
                                </select>
                            </div>
                            <div>
                                <label for="place_of_delivery" class="block text-sm font-medium text-gray-700">Place
                                    of Delivery</label>
                                <input type="text" name="place_of_delivery" id="place_of_delivery"
                                    value="{{ $purchaseRequest->delivery_address }}" readonly
                                    class="mt-1 block w-full border-gray-300 rounded-md shadow-sm bg-gray-100">
                            </div>
                            <div>
                                <label for="delivery_term" class="block text-sm font-medium text-gray-700">Delivery
                                    Term <span class="text-red-500">*</span></label>
                                <input type="text" name="delivery_term" id="delivery_term" required
                                    class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 placeholder-gray-400"
                                    placeholder="e.g., Within 30 days from receipt of PO">
                            </div>
                            <div>
                                <label for="payment_term" class="block text-sm font-medium text-gray-700">Payment Term
                                    <span class="text-red-500">*</span></label>
                                <input type="text" name="payment_term" id="payment_term" required
                                    class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 placeholder-gray-400"
                                    placeholder="e.g., 30 days after delivery">
                            </div>
                            <div>
                                <label for="date_of_delivery" class="block text-sm font-medium text-gray-700">Date of
                                    Delivery <span class="text-red-500">*</span></label>
                                <input type="date" name="date_of_delivery" id="date_of_delivery" required
                                    class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
                            </div>
                        </div>
                    </div>

                    <!-- Item Details Section -->
                    <div class="bg-yellow-50 p-4 rounded-lg">
                        <h3 class="text-lg font-medium text-gray-900 mb-4">Item Details (from PR)</h3>
                        <div
                            style="max-height: 300px; overflow-y: auto; border: 1px solid #e5e7eb; border-radius: 0.5rem; background: white;">
                            <table class="min-w-full divide-y divide-gray-200 text-sm">
                                <thead class="bg-gray-50 sticky top-0">
                                    <tr>
                                        <th class="px-3 py-2 text-left font-semibold text-gray-700">Unit</th>
                                        <th class="px-3 py-2 text-left font-semibold text-gray-700">Qty</th>
                                        <th class="px-3 py-2 text-left font-semibold text-gray-700">Unit Cost</th>
                                        <th class="px-3 py-2 text-left font-semibold text-gray-700">Total Cost</th>
                                        <th class="px-3 py-2 text-left font-semibold text-gray-700">Description</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if ($purchaseRequest->items && $purchaseRequest->items->count() > 0)
                                        @foreach ($purchaseRequest->items as $item)
                                            <tr class="border-b hover:bg-gray-50">
                                                <td class="px-3 py-2 text-sm">{{ $item->unit }}</td>
                                                <td class="px-3 py-2 text-sm">{{ $item->quantity }}</td>
                                                <td class="px-3 py-2 text-sm">
                                                    ₱{{ number_format($item->unit_cost, 2) }}</td>
                                                <td class="px-3 py-2 text-sm">
                                                    ₱{{ number_format($item->total_cost, 2) }}</td>
                                                <td class="px-3 py-2 text-sm"
                                                    style="max-width: 250px; word-wrap: break-word;">
                                                    {{ $item->item_description }}</td>
                                            </tr>
                                        @endforeach
                                        <tr class="bg-gray-50 border-t-2 border-gray-300">
                                            <td class="px-3 py-3 font-semibold text-sm">Grand Total:</td>
                                            <td class="px-3 py-3"></td>
                                            <td class="px-3 py-3"></td>
                                            <td class="px-3 py-3 text-sm font-semibold text-green-600">
                                                ₱{{ number_format($purchaseRequest->total, 2) }}</td>
                                            <td></td>
                                        </tr>
                                    @else
                                        <tr>
                                            <td colspan="5" class="px-3 py-4 text-center text-gray-500">No items
                                                found</td>
                                        </tr>
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- Action Buttons -->
                    <div class="flex justify-end space-x-4 pt-6">
                        <a href="{{ route('staff.pr_review') }}"
                            class="relative bg-gradient-to-r from-gray-500 to-gray-600 text-white font-bold py-2 px-6 rounded-lg
                                   hover:from-gray-600 hover:to-gray-700 hover:shadow-lg hover:scale-105
                                   active:from-gray-700 active:to-gray-800 active:scale-95 active:shadow-inner
                                   transition-all duration-200 ease-in-out transform
                                   before:absolute before:inset-0 before:bg-white before:opacity-0 before:rounded-lg
                                   hover:before:opacity-10 active:before:opacity-20 before:transition-opacity before:duration-200">
                            <svg class="w-4 h-4 inline mr-1" fill="none" stroke="currentColor"
                                viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M6 18L18 6M6 6l12 12"></path>
                            </svg>
                            Cancel
                        </a>
                        <button type="submit"
                            class="relative bg-gradient-to-r from-blue-500 to-blue-600 text-white font-bold py-2 px-6 rounded-lg
                                   hover:from-blue-600 hover:to-blue-700 hover:shadow-lg hover:scale-105
                                   active:from-blue-700 active:to-blue-800 active:scale-95 active:shadow-inner
                                   transition-all duration-200 ease-in-out transform
                                   before:absolute before:inset-0 before:bg-white before:opacity-0 before:rounded-lg
                                   hover:before:opacity-10 active:before:opacity-20 before:transition-opacity before:duration-200">
                            <svg class="w-4 h-4 inline mr-1" fill="none" stroke="currentColor"
                                viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                            </svg>
                            Generate PO
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        function updateSupplierInfo() {
            const supplierSelect = document.getElementById('supplier_id');
            const selectedOption = supplierSelect.options[supplierSelect.selectedIndex];

            if (selectedOption.value) {
                document.getElementById('supplier_address').value = selectedOption.getAttribute('data-address') || '';
                document.getElementById('supplier_tin').value = selectedOption.getAttribute('data-tin') || '';
            } else {
                document.getElementById('supplier_address').value = '';
                document.getElementById('supplier_tin').value = '';
            }
        }
    </script>
</x-page-layout>
