<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\PurchaseRequest;
use App\Models\PurchaseOrder;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Barryvdh\DomPDF\Facade\Pdf;

class ReportsController extends Controller
{
    public function index(Request $request)
    {
        // Get PRs that are approved or completed (only these statuses should be shown)
        $prQuery = PurchaseRequest::with('user', 'status')
            ->whereHas('status', function ($statusQuery) {
                $statusQuery->whereIn('name', ['approved', 'completed']);
            })
            ->whereNotExists(function ($query) {
                $query->select(DB::raw(1))
                    ->from('purchase_orders')
                    ->whereRaw('purchase_orders.purchase_request_id = purchase_requests.id');
            }); // Exclude PRs that have associated POs

        // Get PO data from purchase_orders table
        $poQuery = PurchaseOrder::with(['purchaseRequest.user', 'supplier', 'purchaseRequest.status']);

        // Apply search filters to both queries
        if ($request->filled('search')) {
            $search = $request->search;
            $prQuery->where(function ($q) use ($search) {
                $q->where('pr_number', 'like', "%{$search}%")
                    ->orWhereHas('user', function ($userQuery) use ($search) {
                        $userQuery->where('first_name', 'like', "%{$search}%")
                            ->orWhere('last_name', 'like', "%{$search}%")
                            ->orWhere('middle_name', 'like', "%{$search}%");
                    });
            });

            $poQuery->where(function ($q) use ($search) {
                $q->whereHas('purchaseRequest', function ($prQuery) use ($search) {
                    $prQuery->where('pr_number', 'like', "%{$search}%");
                })
                    ->orWhere('po_number', 'like', "%{$search}%")
                    ->orWhereHas('purchaseRequest.user', function ($userQuery) use ($search) {
                        $userQuery->where('first_name', 'like', "%{$search}%")
                            ->orWhere('last_name', 'like', "%{$search}%")
                            ->orWhere('middle_name', 'like', "%{$search}%");
                    });
            });
        }

        // Apply status filter
        if ($request->filled('status') && $request->status !== 'all') {
            if ($request->status === 'approved') {
                // Only show approved PRs
                $prQuery->whereHas('status', function ($statusQuery) {
                    $statusQuery->where('name', 'approved');
                });
                $poQuery->whereRaw('1 = 0'); // No POs for approved filter
            } elseif ($request->status === 'po_generated') {
                // Only show POs
                $prQuery->whereRaw('1 = 0'); // No PRs for po_generated filter
                // All POs are po_generated by definition
            } elseif ($request->status === 'completed') {
                // Show completed PRs and completed POs
                $prQuery->whereHas('status', function ($statusQuery) {
                    $statusQuery->where('name', 'completed');
                });
                $poQuery->whereNotNull('completed_at');
            }
        }

        // Apply date range filters
        if ($request->filled('date_from')) {
            $prQuery->whereDate('created_at', '>=', $request->date_from);
            $poQuery->whereDate('generated_at', '>=', $request->date_from);
        }
        if ($request->filled('date_to')) {
            $prQuery->whereDate('created_at', '<=', $request->date_to);
            $poQuery->whereDate('generated_at', '<=', $request->date_to);
        }

        // Get results and combine them
        $prs = $prQuery->get()->map(function ($pr) {
            $pr->type = 'PR';
            $pr->document_number = $pr->pr_number;
            $pr->department = $pr->user ? trim($pr->user->first_name . ' ' . ($pr->user->middle_name ?? '') . ' ' . $pr->user->last_name) : '';
            $pr->amount = $pr->total;
            $pr->date_created = $pr->created_at;
            $pr->date_edited = $pr->updated_at;
            return $pr;
        });

        $pos = $poQuery->get()->map(function ($po) {
            $po->type = 'PO';
            $po->document_number = $po->po_number;
            $po->department = $po->purchaseRequest->user ? trim($po->purchaseRequest->user->first_name . ' ' . ($po->purchaseRequest->user->middle_name ?? '') . ' ' . $po->purchaseRequest->user->last_name) : '';
            $po->amount = $po->purchaseRequest->total;
            $po->date_created = $po->generated_at;
            $po->date_edited = $po->updated_at;
            return $po;
        });

        // Combine and sort by date_created desc
        $combined = $prs->concat($pos)->sortByDesc('date_created');

        // Paginate the combined results
        $perPage = 10;
        $currentPage = $request->get('page', 1);
        $reports = new \Illuminate\Pagination\LengthAwarePaginator(
            $combined->forPage($currentPage, $perPage),
            $combined->count(),
            $perPage,
            $currentPage,
            ['path' => $request->url(), 'pageName' => 'page']
        );
        $reports->appends($request->query());

        // Get all available statuses for filter dropdown
        $statuses = \App\Models\Status::where('context', 'purchase_request')
            ->pluck('name');

        $user = auth()->user();
        $recentActivities = $user->activities()
            ->orderBy('created_at', 'desc')
            ->limit(10)
            ->get();

        return view('admin.reports', compact('reports', 'statuses', 'recentActivities'));
    }

    public function export(Request $request)
    {
        $format = $request->input('format', 'xlsx');

        // Get the same data as the index method with filters applied
        $reports = $this->getFilteredReports($request);

        if ($format === 'xlsx') {
            return $this->exportToCsv($reports, $request);
        } elseif ($format === 'pdf') {
            return $this->exportToPdf($reports, $request);
        }

        return response()->json(['error' => 'Invalid format'], 400);
    }
    private function getFilteredReports(Request $request)
    {
        // Same logic as index method to get filtered data
        $prQuery = PurchaseRequest::with('user', 'status')
            ->whereHas('status', function ($statusQuery) {
                $statusQuery->whereIn('name', ['approved', 'completed']);
            })
            ->whereNotExists(function ($query) {
                $query->select(DB::raw(1))
                    ->from('purchase_orders')
                    ->whereRaw('purchase_orders.purchase_request_id = purchase_requests.id');
            }); // Exclude PRs that have associated POs

        $poQuery = PurchaseOrder::with(['purchaseRequest.user', 'supplier', 'purchaseRequest.status']);

        // Apply filters
        if ($request->filled('search')) {
            $search = $request->search;
            $prQuery->where(function ($q) use ($search) {
                $q->where('pr_number', 'like', "%{$search}%")
                    ->orWhereHas('user', function ($userQuery) use ($search) {
                        $userQuery->where('first_name', 'like', "%{$search}%")
                            ->orWhere('last_name', 'like', "%{$search}%")
                            ->orWhere('middle_name', 'like', "%{$search}%");
                    });
            });

            $poQuery->where(function ($q) use ($search) {
                $q->whereHas('purchaseRequest', function ($prQuery) use ($search) {
                    $prQuery->where('pr_number', 'like', "%{$search}%");
                })
                    ->orWhere('po_number', 'like', "%{$search}%")
                    ->orWhereHas('purchaseRequest.user', function ($userQuery) use ($search) {
                        $userQuery->where('first_name', 'like', "%{$search}%")
                            ->orWhere('last_name', 'like', "%{$search}%")
                            ->orWhere('middle_name', 'like', "%{$search}%");
                    });
            });
        }

        if ($request->filled('status') && $request->status !== 'all') {
            if ($request->status === 'approved') {
                // Only show approved PRs
                $prQuery->whereHas('status', function ($statusQuery) {
                    $statusQuery->where('name', 'approved');
                });
                $poQuery->whereRaw('1 = 0'); // No POs for approved filter
            } elseif ($request->status === 'po_generated') {
                // Only show POs
                $prQuery->whereRaw('1 = 0'); // No PRs for po_generated filter
                // All POs are po_generated by definition
            } elseif ($request->status === 'completed') {
                // Show completed PRs and completed POs
                $prQuery->whereHas('status', function ($statusQuery) {
                    $statusQuery->where('name', 'completed');
                });
                $poQuery->whereNotNull('completed_at');
            }
        }

        if ($request->filled('date_from')) {
            $prQuery->whereDate('created_at', '>=', $request->date_from);
            $poQuery->whereDate('generated_at', '>=', $request->date_from);
        }
        if ($request->filled('date_to')) {
            $prQuery->whereDate('created_at', '<=', $request->date_to);
            $poQuery->whereDate('generated_at', '<=', $request->date_to);
        }

        // Get results and combine them
        $prs = $prQuery->get()->map(function ($pr) {
            $pr->type = 'PR';
            $pr->document_number = $pr->pr_number;
            $pr->department = $pr->user ? trim($pr->user->first_name . ' ' . ($pr->user->middle_name ?? '') . ' ' . $pr->user->last_name) : '';
            $pr->amount = $pr->total;
            $pr->date_created = $pr->created_at;
            $pr->date_edited = $pr->updated_at;
            return $pr;
        });

        $pos = $poQuery->get()->map(function ($po) {
            $po->type = 'PO';
            $po->document_number = $po->po_number;
            $po->department = $po->purchaseRequest->user ? trim($po->purchaseRequest->user->first_name . ' ' . ($po->purchaseRequest->user->middle_name ?? '') . ' ' . $po->purchaseRequest->user->last_name) : '';
            $po->amount = $po->purchaseRequest->total;
            $po->date_created = $po->generated_at;
            $po->date_edited = $po->updated_at;
            return $po;
        });

        // Combine and sort by date_created desc
        $combined = $prs->concat($pos)->sortByDesc('date_created');

        return $combined;
    }

    private function exportToCsv($reports, Request $request)
    {
        // Create CSV content
        $csvContent = [];
        $csvContent[] = [
            'Counter',
            'Type',
            'Document Number',
            'Department',
            'Status',
            'Amount'
        ];

        $counter = 1;
        foreach ($reports as $report) {
            $csvContent[] = [
                $counter++,
                $report->type,
                $report->document_number,
                $report->department,
                $report->type === 'PO' ? 'PO Generated' : ucfirst(str_replace('_', ' ', $report->status)),
                '₱' . number_format($report->amount, 2)
            ];
        }

        // Create CSV file
        $filename = 'reports_' . date('Y-m-d_H-i-s') . '.csv';
        $handle = fopen('php://temp', 'r+');

        foreach ($csvContent as $row) {
            fputcsv($handle, $row);
        }

        rewind($handle);
        $csvData = stream_get_contents($handle);
        fclose($handle);

        return response($csvData)
            ->header('Content-Type', 'text/csv')
            ->header('Content-Disposition', 'attachment; filename="' . $filename . '"');
    }
    private function exportToPdf($reports, Request $request)
    {
        $data = [
            'reports' => $reports,
            'filters' => [
                'search' => $request->search,
                'status' => $request->status,
                'date_from' => $request->date_from,
                'date_to' => $request->date_to,
            ],
            'exported_at' => now()->format('F j, Y g:i A')
        ];

        $pdf = Pdf::loadView('exports.reports_pdf', $data);
        $filename = 'reports_' . now()->format('Y-m-d_H-i-s') . '.pdf';

        return $pdf->download($filename);
    }

    public function getPRData($id)
    {
        $pr = PurchaseRequest::with(['user', 'items'])->findOrFail($id);

        return response()->json([
            'id' => $pr->id,
            'pr_number' => $pr->pr_number,
            'entity_name' => $pr->entity_name,
            'fund_cluster' => $pr->fund_cluster,
            'office_section' => $pr->office_section,
            'responsibility_center_code' => $pr->responsibility_center_code,
            'date' => $pr->date ? $pr->date->format('M d, Y') : '',
            'purpose' => $pr->purpose,
            'total' => $pr->total,
            'status' => $pr->status,
            'status_color' => $pr->status_color,
            'status_display' => $pr->status_display,
            'requested_by_name' => $pr->user ? $pr->user->first_name .
                ($pr->user->middle_name ? ' ' . $pr->user->middle_name : '') .
                ' ' . $pr->user->last_name : '',
            'delivery_address' => $pr->delivery_address,
            'delivery_period' => $pr->delivery_period,
            'items' => $pr->items->map(function ($item) {
                return [
                    'unit' => $item->unit,
                    'quantity' => $item->quantity,
                    'unit_cost' => $item->unit_cost,
                    'total_cost' => $item->total_cost,
                    'item_description' => $item->item_description,
                ];
            })
        ]);
    }

    public function getPOData($id)
    {
        $po = PurchaseOrder::with(['purchaseRequest.user', 'supplier'])->findOrFail($id);
        $pr = $po->purchaseRequest;

        return response()->json([
            'id' => $po->id,
            'pr_number' => $pr->pr_number,
            'po_number' => $po->po_number,
            'supplier_name' => $po->supplier->supplier_name ?? '',
            'supplier_address' => $po->supplier->address ?? '',
            'supplier_tin' => $po->supplier->tin ?? '',
            'mode_of_procurement' => $po->mode_of_procurement,
            'place_of_delivery' => $pr->delivery_address,
            'delivery_term' => $po->delivery_term,
            'payment_term' => $po->payment_term,
            'date_of_delivery' => $po->date_of_delivery ? $po->date_of_delivery->format('M d, Y') : '',
            'po_generated_at' => $po->generated_at ? $po->generated_at->format('M d, Y') : '',
            'requesting_unit' => $pr->user ? $pr->user->first_name .
                ($pr->user->middle_name ? ' ' . $pr->user->middle_name : '') .
                ' ' . $pr->user->last_name : '',
            'status' => $pr->status, // Use actual PR status
            'status_color' => $pr->status_color,
            'purpose' => $pr->purpose,
            'delivery_address' => $pr->delivery_address,
            'delivery_period' => $pr->delivery_period,
            'requested_by_name' => $pr->user ? $pr->user->first_name .
                ($pr->user->middle_name ? ' ' . $pr->user->middle_name : '') .
                ' ' . $pr->user->last_name : '',
            'items' => $pr->items->map(function ($item) {
                return [
                    'unit' => $item->unit,
                    'quantity' => $item->quantity,
                    'unit_cost' => $item->unit_cost,
                    'total_cost' => $item->total_cost,
                    'item_description' => $item->item_description,
                ];
            })
        ]);
    }
}
