<?php

namespace Tests\Unit;

use App\Models\PurchaseOrder;
use App\Models\PurchaseRequest;
use App\Models\Supplier;
use App\Models\User;
use App\Models\Status;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Tests\SeedsRoles;

class PurchaseOrderTest extends TestCase
{
    use RefreshDatabase, SeedsRoles;

    protected function setUp(): void
    {
        parent::setUp();
        $this->seedRoles();
        $this->seedStatuses();
        $this->seedUnits();
    }

    /**
     * Test purchase order can be created with valid data.
     */
    public function test_purchase_order_can_be_created(): void
    {
        $pr = PurchaseRequest::factory()->create();
        $supplier = Supplier::factory()->create();
        $user = User::factory()->create(['role_id' => $this->getRoleId('staff')]);
        $status = Status::where('context', 'procurement')->where('name', 'po_generated')->first();

        $po = PurchaseOrder::create([
            'purchase_request_id' => $pr->id,
            'supplier_id' => $supplier->id,
            'po_number' => 'PO-2025-001',
            'mode_of_procurement' => 'Public Bidding',
            'delivery_term' => '30 days',
            'payment_term' => 'Net 30',
            'date_of_delivery' => now()->addDays(30),
            'status_id' => $status->id,
            'generated_by' => $user->id,
            'generated_at' => now(),
        ]);

        $this->assertDatabaseHas('purchase_orders', [
            'po_number' => 'PO-2025-001',
            'purchase_request_id' => $pr->id,
            'supplier_id' => $supplier->id,
        ]);
    }

    /**
     * Test purchase order belongs to purchase request.
     */
    public function test_purchase_order_belongs_to_purchase_request(): void
    {
        $pr = PurchaseRequest::factory()->create();
        $po = PurchaseOrder::factory()->create(['purchase_request_id' => $pr->id]);

        $this->assertInstanceOf(PurchaseRequest::class, $po->purchaseRequest);
        $this->assertEquals($pr->id, $po->purchaseRequest->id);
    }

    /**
     * Test purchase order belongs to supplier.
     */
    public function test_purchase_order_belongs_to_supplier(): void
    {
        $supplier = Supplier::factory()->create();
        $po = PurchaseOrder::factory()->create(['supplier_id' => $supplier->id]);

        $this->assertInstanceOf(Supplier::class, $po->supplier);
        $this->assertEquals($supplier->id, $po->supplier->id);
    }

    /**
     * Test purchase order belongs to generated by user.
     */
    public function test_purchase_order_belongs_to_generated_by_user(): void
    {
        $user = User::factory()->create();
        $po = PurchaseOrder::factory()->create(['generated_by' => $user->id]);

        $this->assertInstanceOf(User::class, $po->generatedBy);
        $this->assertEquals($user->id, $po->generatedBy->id);
    }

    /**
     * Test purchase order dates are cast correctly.
     */
    public function test_purchase_order_casts_dates_correctly(): void
    {
        $po = PurchaseOrder::factory()->create([
            'generated_at' => '2025-01-15 10:30:00',
            'date_of_delivery' => '2025-02-15',
        ]);

        $this->assertInstanceOf(\Illuminate\Support\Carbon::class, $po->generated_at);
        $this->assertInstanceOf(\Illuminate\Support\Carbon::class, $po->date_of_delivery);
    }

    /**
     * Test purchase order can be marked as completed.
     */
    public function test_purchase_order_can_be_completed(): void
    {
        $completedStatus = Status::where('context', 'procurement')->where('name', 'completed')->first();
        $po = PurchaseOrder::factory()->create(['completed_at' => null]);

        $po->update([
            'status_id' => $completedStatus->id,
            'completed_at' => now()
        ]);

        $this->assertEquals($completedStatus->id, $po->status_id);
        $this->assertNotNull($po->completed_at);
    }

    /**
     * Test purchase order requires purchase request.
     */
    public function test_purchase_order_requires_purchase_request(): void
    {
        $this->expectException(\Illuminate\Database\QueryException::class);

        PurchaseOrder::create([
            'po_number' => 'PO-2025-001',
            'supplier_id' => 1,
            // Missing purchase_request_id
        ]);
    }
}
